In [4]:
import numpy as np

In [5]:
class TicTacToe:
    def __init__(self):
        self.r_c=3
        self.c_c=3
        self.action_size=self.r_c*self.c_c

    def startState(self):
        return np.zeros((self.r_c,self.c_c))

    def nextState(self,state,action,player):
        row=action//self.c_c
        col=action%self.c_c
        state[row,col]=player
        return state

    def get_valid_moves(self,state):
        return (state.reshape(-1)==0).astype(np.uint8)

    def checkWin(self,state,action):
        row=action//self.c_c
        col=action%self.c_c
        player=state[row,col]
        return( np.sum(state[row,:])==player*self.c_c 
                or np.sum(state[:,col])==player*self.r_c 
                or np.sum(np.diag(state))==player*self.r_c 
                or np.sum(np.diag(np.flip(state,axis=0)))==player*self.r_c 
        )

    def get_value_and_terminated(self, state, action):
        if self.checkWin(state, action):
            return 1, True
        if np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        return 0, False
    
    def opp_player(self,player):
        return -player

In [7]:
tictactoe=TicTacToe()
player=1
state=tictactoe.startState()
while True:
    print(state)
    validMoves=tictactoe.get_valid_moves(state)
    print("Valid Moves: ",[i for i in range(tictactoe.action_size) if validMoves[i]==1])
    action=int(input("Enter action: "))
    try:
        if validMoves[action]==0:
            print("action not valid")
            continue
    except:
        print("action not valid")
        continue
    state=tictactoe.nextState(state,action,player)
    value,isterminated=tictactoe.get_value_and_terminated(state,action)
    if isterminated:
        if value==1:
            print(player," won")
        else:
            print("draw")
        break
    player=tictactoe.opp_player(player)

print(state)
    

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Valid Moves:  [0, 1, 2, 3, 4, 5, 6, 7, 8]


Enter action:  1


[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Valid Moves:  [0, 2, 3, 4, 5, 6, 7, 8]


Enter action:  2


[[ 0.  1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Valid Moves:  [0, 3, 4, 5, 6, 7, 8]


Enter action:  4


[[ 0.  1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
Valid Moves:  [0, 3, 5, 6, 7, 8]


Enter action:  5


[[ 0.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]
Valid Moves:  [0, 3, 6, 7, 8]


Enter action:  7


1  won
[[ 0.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  1.  0.]]
